### PR TITLE
Cleaned up modman file

### PR DESCRIPTION
**Pull request by jharrisonau**
Cleaned up the modman file because I was getting some composer errors when trying to install, looks like some files don't exist anymore.

### CODE REVIEW

**Comment by LeeSaferite** [comment]
Using the * syntax breaks usage in the hackatoin composer installer.

**Comment by jharrisonau** [comment]
Are you sure? We use the hackathon composer for all our sites and the *
syntax works fine. We are using my changes in production sites with no
issues.

**Comment by LeeSaferite** [comment]
Hmm, I seem to recall an issue, but I'll have to go research it now. :)

In any case, the * syntax is really not needed in this case and is less clear than just being explicit.

**Comment by thaiphan** [comment]
Hey Lee, what's the static of this pull request? Are you able to merge it in?

**Comment by amacgregor** [comment]
This pull request is no longer necesary since it has been fixed on a Pull Request by Lee

**Pull request closed without merging**
